### ISSUE TITLE
ModuleNotFoundError when installing from source

### ISSUE THREAD

**Issue by lhenault** [lhenault/simpleAI#14]
@Nintorac FYI on a clean install there is a `ModuleNotFoundError` with : 

`packages = [{include = "src/simple_ai"}]`

Changing it to :

`packages = [{include = "simple_ai", from = "src"}]`

Fixes it (as suggested [here](https://python-poetry.org/docs/pyproject/#packages)).

**Comment by Nintorac** [comment]
yea, this and a few other fixes stuck in the rwkv branch that I should have pulled into a seperate PR! :s
