### ISSUE TITLE
The structure of the json result is not correct

### ISSUE THREAD

**Issue by cahya-wirawan** [lhenault/simpleAI#29]
Hi,

Meanwhile I was able run the RWKV grpc server from @Nintorac and using the web interface https://github.com/Niek/chatgpt-web. But there was an issue with json answer (the **content** part) sent from simpleai to the browser after I submit the chat message.
The json result looks like following:

```
{
  ...
  "choices": [
    {
      "role": "assistant",
      "index": 0,
      "message": {
        "role": "assistant",
        "content": {
          "role": "raven",
          "content": "Result from LM"
        }
      },
      "finish_reason": "stop"
    }
  ],
  ...
  }
}

```
The json should look like following actually:

```
{
  ...
  "choices": [
    {
      "role": "assistant",
      "index": 0,
      "message": {
        "role": "raven",
        "content": "Result from LM"
      },
      "finish_reason": "stop"
    }
  ],
  ...
}

```
The bug could be either in file utils.py or in examples/Raven-RWKV/model.py in chat function. For time being I fixed the utils.c as follow:
```
$ git diff ../src/simple_ai/utils.py 
diff --git a/src/simple_ai/utils.py b/src/simple_ai/utils.py
index 82fa565..62058e6 100644
--- a/src/simple_ai/utils.py
+++ b/src/simple_ai/utils.py
@@ -74,10 +74,10 @@ def format_chat_response(model_name: str, predictions, usage=dummy_usage) -> dic
             {
                 "role": "assistant",
                 "index": idx,
-                "message": {"role": "assistant", "content": text},
+                "message": message,
                 "finish_reason": "stop",
             }
-            for idx, text in enumerate(predictions)
+            for idx, message in enumerate(predictions)
         ],
         "usage": usage,
     }
```
After I fixed it, I can use the chatgpt-web with RWKV model.

**Comment by cahya-wirawan** [comment]
btw, there are too many "role": "assistant", in the result. If I see the result from openai, the "role" is only inside "message" key.

**Comment by cahya-wirawan** [comment]
But I think it’s better if I fix the file examples/Raven-RWKV/model.py instead of src/simple_ai/utils.py

**Comment by Nintorac** [comment]
Ooh yea, I think the appropriate fix is to modify utils. The message object for chat was updated to accommodate streaming responses so the response should be a list of role, content pairs

https://github.com/lhenault/simpleAI/blob/main/src/simple_ai/api/grpc/protos/llm_chat.proto#L43-L47

**Comment by cahya-wirawan** [comment]
Ok thanks for the info

**Comment by lhenault** [comment]
Yep, agree we should just fix the formatting function in `utils.py`. 

Just to confirm as I'm a bit lost, if we change `format_chat_response` to what you @cahya-wirawan propose, it would fix the non-stream chat output while keeping the streaming response correct?

Similarly, the `/edits` should be updated now that we have the new `chat` interface. We:

- are still using a combination of `add_instructions` on API side and a `complete` method model side, 
- should rather send a list of `(role, content)` and process them through `add_instructions` or a custom function model side.
