### ISSUE TITLE
Issue with Loading MPT-7B on Titan-X GPU - Potential Device Map Solution

### ISSUE THREAD

**Issue by danielvasic** [lhenault/simpleAI#49]
Hey @lhenault ,

First off, kudos on the Python package - it's been a real game-changer for my projects.

I've hit a bit of a snag though. I'm trying to load the MPT-7B model onto my Titan-X GPU, but it seems to be loading into RAM instead. Weirdly enough, I managed to get the Alpaca Lora 7B model loaded up, but it only works on the edit route. Any other route and I get an 'index out of bounds' exception. I'm guessing it's because Alpaca only supports the Instruct API and not the Chat or Completion APIs. So, I tried switching to MPT-7B.Chat, but no dice - can't get the model into memory.

I came across a [StackOverflow discussion](https://stackoverflow.com/questions/75459172/loading-a-huggingface-model-on-multiple-gpus-using-model-parallelism-for-inferen) that suggested using a device map when loading the model. Sounds like it might do the trick, but I wanted to run it by you first.

Do you think this could solve my problem? Any advice would be super appreciated!

Best,

**Comment by lhenault** [comment]
Hey @danielvasic, thanks for the kind words, I'm glad this project is useful to you!

From what I've seen, the MPT-7B model is using about 16GB of VRAM on the GPU (+ a few extra ones for the inputs), so a Titan X wouldn't be enough (correct me if I'm wrong but these "only" have 12GB). 

In your original comment you mention having 2 Titan X available, so using them together through `device_map="auto"` should give you 24GB of VRAM, enough for you to load and use that model, if that works as suggested by your link. I'd give it a try if I were you, let me know how it goes.

**Comment by lhenault** [comment]
BTW, current file `models.py` L80 loads the model on the first available GPU:

```python
    ).to(device)
```

I believe you should comment and / or remove this part to use all of them.

**Comment by danielvasic** [comment]
Actually I have two GPU-s, one is Titan X (with 12GB VRAM as you suggested) and the other is Quadro K2200 (with 4GB VRAM) that would be just enough to load the model, I will give it a try and report back.

On another note, how can I use llama-7B-lora with openai Python API, i have tried this example but I get 500 server error:

```
import openai

# Put anything you want in `API key`
openai.api_key = 'Free the models'

# Point to your own url
openai.api_base = "http://127.0.0.1:8080"

# Do your usual things, for instance a completion query:
print(openai.Model.list())
completion = openai.Completion.create(model="llama-7B", prompt="Hello everyone this is")

```

**Comment by lhenault** [comment]
So for the Alpaca model you're mentioning, it is an instruct model, you should rather use [`Edits`](https://platform.openai.com/docs/api-reference/edits), not ˋCompletions` with this one, make sure that the model is correctly defined in your `models.toml` file, and that you are using the correct name.

**Comment by lhenault** [comment]
I have to admit I haven't tried this one through the official client, and examples are definitely lacking, but [there is a `Edit` interface in it](https://github.com/openai/openai-python/blob/0abf64137c18b45925d5015bae80429adb46fac6/openai/api_resources/edit.py).

**Comment by danielvasic** [comment]
Thanks @lhenault,

Thanks very much I tried `edits` not edit, also on the side note If anyone wants to use ChatCompletion API the OpenAssistant example described in Your [blog post](thttps://louishenault.com/p/chatdiy-build-your-own-chatgpt-at-home/) works fine. I only had to define the `offload_folder` parameter and create the directory for it.
