### ISSUE TITLE
How to add custom endpoint?

### ISSUE THREAD

**Issue by Youho99** [lhenault/simpleAI#56]
I would like to add a new custom endpoint.

Is there a way to do this easily? for example by entering the information in a custom script (like for adding /v1/ for example)?

**Comment by lhenault** [comment]
Hi @Youho99 !

Yes you can, for instance using something like:

```python
import uvicorn
from simple_ai.server import app
from fastapi import APIRouter

router = APIRouter()

async def hello():
    return {"Hello": "World"}

router.add_api_route("/hello", hello, methods=["GET"])
app.include_router(router)

def serve_app(app=app, host="0.0.0.0", port=8080):
    uvicorn.run(app=app, host=host, port=port)
    
if __name__ == "__main__":
    serve_app()
```

Will add it to the docs eventually, it's a good point.
