### ISSUE TITLE
On-the-fly modification of OpenAI endpoint actions

### ISSUE THREAD

**Issue by Youho99** [lhenault/simpleAI#57]
My goal is to log the responses from the API when I make a chat/completions request (only the text response).
So write this response in a “vlm_response.log” file.
Knowing that this log file will be automatically created in the gRPC module launch file (custom file replacing "simple_ai serve")

Is there a way to modify the action done in the endpoint on the fly, without touching the library? The best would be to make modifications only in the custom file used to launch the gRPC module.

**Comment by lhenault** [comment]
I think you can try to use a FastAPI middleware or a custom APIRoute, see [this SO thread](https://stackoverflow.com/questions/69670125/how-to-log-raw-http-request-response-in-python-fastapi) for more details.

**Comment by Youho99** [comment]
it's works with middleware
