### ISSUE TITLE
Annotated not available until python 3.9

### ISSUE THREAD

**Issue by Nintorac** [lhenault/simpleAI#9]
It's used in `src/simple_ai/server.py`

It prevents the Dockerfiles in the examples from running a fast api server and conflicts with the pyproject dependency of  `python = "^3.8"`

edit: and `tomllib` at python 3.11

**Comment by lhenault** [comment]
Any suggestion here? I'd be fine with `python = "^3.9"`, annotations are quite helpful even if just a nice to have.

3.11 would be good too but maybe too recent for some, we could rely on [`tomli`](https://github.com/hukkin/tomli) for older versions.

**Comment by Nintorac** [comment]
No strong opinions either way, `"^3.9"` sounds good.

It looks like conditional dependencies are a thing too https://www.b-list.org/weblog/2022/nov/08/python-311-gotcha/

**Comment by lhenault** [comment]
Should be fixed by #10
